<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mercadopago/dx-php' => array(
            'pretty_version' => '3.5.1',
            'version' => '3.5.1.0',
            'reference' => '657be1bf17b08b3c887891245825e56111006883',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mercadopago/dx-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mercadopago/sdk' => array(
            'pretty_version' => 'v0.5.6',
            'version' => '0.5.6.0',
            'reference' => '67f65735d5d720a7fc2569163f5c7d150adc613d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mercadopago/sdk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
